spring:
  application:
    name: auric-backend

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate        # or update temporarily if schema not there yet
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: UTC
      defer-datasource-initialization: true
    open-in-view: false

  sql:
    init:
      mode: never       # don't run schema/data.sql
      platform: mysql

  flyway:
    enabled: false      # <-- THIS is the important line

security:
  jwt:
    secret: "change-this-to-a-256-bit-random-string"
    access-token-minutes: 60
    refresh-token-days: 7

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"

springdoc:
  swagger-ui:
    path: /swagger-ui
    custom-css: swagger-ui/swagger-ui-custom.css

logging:
  level:
    org.springframework.jdbc.datasource.init: DEBUG
    org.springframework.security: DEBUG
